"""empty message

Revision ID: 3fcc06fc9fb0
Revises: e1dba66d7e3d
Create Date: 2020-08-26 11:39:56.055120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcc06fc9fb0'
down_revision = 'e1dba66d7e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('actors_movie_id_fkey', 'actors', type_='foreignkey')
    op.create_foreign_key(None, 'actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'actors', type_='foreignkey')
    op.create_foreign_key('actors_movie_id_fkey', 'actors', 'movies', ['movie_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
