"""empty message

Revision ID: e1dba66d7e3d
Revises: 206bad04ab65
Create Date: 2020-08-25 20:21:47.872140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1dba66d7e3d'
down_revision = '206bad04ab65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performances')
    op.drop_table('Performances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Performances',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Performances_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['actors.id'], name='Performances_artist_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='Performances_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Performances_pkey')
    )
    op.create_table('performances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name='performances_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='performances_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='performances_pkey')
    )
    # ### end Alembic commands ###
